import { describe, expect, it } from "vitest";

import { largestVariantUrl, originalImageUrl } from "./image-urls";
import { asImageId, type ImageMetadata } from "./image-types";

function image(overrides: Partial<ImageMetadata> = {}): ImageMetadata {
  return {
    id: asImageId("abc1234567890def"),
    alt: "A photo",
    width: 2400,
    height: 1600,
    placeholderDataUri: "data:image/webp;base64,AAAA",
    contentSlug: "home",
    originalExt: "jpg",
    ...overrides,
  };
}

describe("originalImageUrl", () => {
  it("composes the on-disk path from contentSlug + id + extension", () => {
    expect(originalImageUrl(image())).toBe(
      "/images/home/abc1234567890def/original.jpg",
    );
  });

  it("preserves the original extension (svg / png / etc.)", () => {
    expect(originalImageUrl(image({ originalExt: "svg" }))).toBe(
      "/images/home/abc1234567890def/original.svg",
    );
    expect(originalImageUrl(image({ originalExt: "png" }))).toBe(
      "/images/home/abc1234567890def/original.png",
    );
  });
});

describe("largestVariantUrl", () => {
  it("picks the largest sharp variant ≤ source width", () => {
    // Source width 2400 → all three variants (400/800/1600) qualify.
    expect(largestVariantUrl(image())).toBe(
      "/images/home/abc1234567890def/1600.webp",
    );
  });

  it("picks 800 when the source is between 800 and 1600", () => {
    expect(largestVariantUrl(image({ width: 1024 }))).toBe(
      "/images/home/abc1234567890def/800.webp",
    );
  });

  it("falls back to the original when source < smallest variant", () => {
    // 256×256 favicon-style upload: no variants generated by the
    // pipeline (`withoutEnlargement: true`).
    expect(largestVariantUrl(image({ width: 256 }))).toBe(
      "/images/home/abc1234567890def/original.jpg",
    );
  });

  it("uses the original for SVG (vector pipeline bypass)", () => {
    expect(largestVariantUrl(image({ originalExt: "svg" }))).toBe(
      "/images/home/abc1234567890def/original.svg",
    );
  });

  it("uses the original for ICO", () => {
    expect(largestVariantUrl(image({ originalExt: "ico" }))).toBe(
      "/images/home/abc1234567890def/original.ico",
    );
  });

  it("accepts an explicit format argument (avif)", () => {
    // Used by future `<picture>`-based underlays that emit both
    // formats. Today the photo lightbox + page background just
    // use the webp default.
    expect(largestVariantUrl(image(), "avif")).toBe(
      "/images/home/abc1234567890def/1600.avif",
    );
  });
});
