/**
 * Curated theme presets for the first-run wizard (ADR-013, tokenized themes).
 *
 * A theme bundles a complete Appearance — palette + typography + the design
 * token group (layout / shape / detail) — with a header *style* into one
 * named, one-click choice. Presets reuse the `Appearance` and `HeaderConfig`
 * shapes from `site-config-types`; no new token vocabulary.
 *
 * A theme deliberately does NOT define the `wordmark` image or the
 * `headerSubtitle`: those are artist-owned and must survive a theme change
 * (see `resolveTheme`).
 *
 * `THEME_IDS` is the single source of truth; the `Record<ThemeId, …>` shape of
 * `THEME_PRESETS` makes TypeScript enforce exactly one preset per id.
 * `DEFAULT_THEME_ID` is applied for the "start empty" path and as the fallback.
 *
 * The 15 directions are translated from the design comps in
 * `design/theme-comps/` (the structure archetypes `frame`/`card` are page
 * layouts, not themes, so they aren't presets).
 */
import { type Appearance, type HeaderConfig } from "./site-config-types";

export const THEME_IDS = [
  "meadow",
  "riot",
  "paper",
  "aurora",
  "vinyl",
  "ink",
  "ember",
  "redwood",
  "mahogany",
  "oak",
  "pulse",
  "concrete",
  "candy",
  "obsidian",
  "cobalt",
] as const;
export type ThemeId = (typeof THEME_IDS)[number];

export const DEFAULT_THEME_ID: ThemeId = "meadow";

/**
 * The header fields a theme controls — the *style* of the header, not its
 * content. `wordmark` + `headerSubtitle` are excluded so applying a theme
 * never wipes them.
 */
export type HeaderStyle = Pick<
  HeaderConfig,
  | "headerMode"
  | "headerLayout"
  | "wordmarkSizeAdjust"
  | "headerForegroundColor"
  | "isHeaderTextUppercase"
>;

export interface ThemePreset {
  /** Display name for the picker card. */
  name: string;
  /** One-line description for the picker card. */
  description: string;
  appearance: Appearance;
  header: HeaderStyle;
}

const NO_GRADIENT = { from: "", via: "", to: "" };

export const THEME_PRESETS: Record<ThemeId, ThemePreset> = {
  meadow: {
    name: "Meadow",
    description: "Wholesome warm folk — sage, terracotta, and amber on soft cream.",
    appearance: {
      colors: {
        primary: "#3f5135",
        secondary: "#cf9248",
        accent: "#bf6b3a",
        linkColor: "",
        background: "#fbf7f0",
        surface: "#ffffff",
        text: "#3a342c",
        textMuted: "#7a7165",
        border: "#e4ddd0",
      },
      typography: {
        bodyFont: "Nunito Sans",
        headingMode: "split",
        headingFont: "Fraunces",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 700 },
        headingWeights: { h1: 600, h2: 600, h3: 600 },
      },
      design: {
        density: "spacious",
        contentWidth: "medium",
        sectionAlign: "left",
        gutter: "airy",
        radius: "round",
        buttonShape: "pill",
        buttonFill: "solid",
        shadowStyle: "soft",
        ruleStyle: "hairline",
        imageTreatment: "rounded",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "normal",
        headingScale: "balanced",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#ffffff",
        footerStyle: "inverse",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: false,
    },
  },
  riot: {
    name: "Riot",
    description: "Edgy DIY punk — acid lime on black, oversized condensed caps.",
    appearance: {
      colors: {
        primary: "#f2f2f2",
        secondary: "#c8ff2f",
        accent: "#c8ff2f",
        linkColor: "",
        background: "#0a0a0a",
        surface: "#161616",
        text: "#f2f2f2",
        textMuted: "#8a8a8a",
        border: "#2a2a2a",
      },
      typography: {
        bodyFont: "Space Mono",
        headingMode: "split",
        headingFont: "Anton",
        displayFont: "Anton",
        bodyWeights: { body: 400, bodyBold: 700 },
        headingWeights: { h1: 400, h2: 400, h3: 400 },
      },
      design: {
        density: "compact",
        contentWidth: "wide",
        sectionAlign: "left",
        gutter: "tight",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "solid",
        shadowStyle: "hard-offset",
        ruleStyle: "bold",
        imageTreatment: "plain",
        galleryLayout: "grid",
        headingCase: "upper",
        headingTracking: "tight",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#0a0a0a",
        footerStyle: "surface",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: true,
    },
  },
  paper: {
    name: "Paper",
    description: "Minimal editorial — black on white, dramatic Playfair display.",
    appearance: {
      colors: {
        primary: "#111111",
        secondary: "#111111",
        accent: "#555555",
        linkColor: "",
        background: "#ffffff",
        surface: "#ffffff",
        text: "#1a1a1a",
        textMuted: "#737373",
        border: "#e6e6e6",
      },
      typography: {
        bodyFont: "Inter",
        headingMode: "split",
        headingFont: "Playfair Display",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 600 },
        headingWeights: { h1: 700, h2: 700, h3: 600 },
      },
      design: {
        density: "spacious",
        contentWidth: "narrow",
        sectionAlign: "center",
        gutter: "airy",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "underline",
        shadowStyle: "none",
        ruleStyle: "hairline",
        imageTreatment: "plain",
        galleryLayout: "masonry",
        headingCase: "none",
        headingTracking: "normal",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#ffffff",
        footerStyle: "surface",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-center-nav-below",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: false,
    },
  },
  aurora: {
    name: "Aurora",
    description: "Dreamy pastel — Cormorant serif on a hazy, muted lavender.",
    appearance: {
      colors: {
        primary: "#3a2f5c",
        secondary: "#e0709e",
        accent: "#7b6cd9",
        linkColor: "",
        background: "#e9e6ef",
        surface: "#f4f1f8",
        text: "#2a2740",
        textMuted: "#736f88",
        border: "#dad4e4",
      },
      typography: {
        bodyFont: "Inter",
        headingMode: "split",
        headingFont: "Cormorant Garamond",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 500, h2: 500, h3: 500 },
      },
      design: {
        density: "spacious",
        contentWidth: "medium",
        sectionAlign: "center",
        gutter: "normal",
        radius: "round",
        buttonShape: "pill",
        buttonFill: "underline",
        shadowStyle: "glow",
        ruleStyle: "hairline",
        imageTreatment: "rounded",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "normal",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#ffffff",
        footerStyle: "surface",
        grain: true,
      },
    },
    header: {
      headerMode: "transparent-static",
      headerLayout: "logo-center-nav-below",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "#ffffff",
      isHeaderTextUppercase: false,
    },
  },
  vinyl: {
    name: "Vinyl",
    description: "Refined warm analog — rust, ochre, and espresso on oat.",
    appearance: {
      colors: {
        primary: "#a9542c",
        secondary: "#bd8a3a",
        accent: "#a9542c",
        linkColor: "",
        background: "#efe7d4",
        surface: "#f7f0df",
        text: "#2c2118",
        textMuted: "#8a7a63",
        border: "#ddd0b4",
      },
      typography: {
        bodyFont: "DM Sans",
        headingMode: "split",
        headingFont: "Bricolage Grotesque",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 600, h2: 600, h3: 600 },
      },
      design: {
        density: "comfortable",
        contentWidth: "medium",
        sectionAlign: "left",
        gutter: "normal",
        radius: "soft",
        buttonShape: "rounded",
        buttonFill: "solid",
        shadowStyle: "soft",
        ruleStyle: "hairline",
        imageTreatment: "framed",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "tight",
        headingScale: "balanced",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#f7f0df",
        footerStyle: "inverse",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: true,
    },
  },
  ink: {
    name: "Ink",
    description: "Dark editorial — luminous Playfair on near-black, gallery-quiet.",
    appearance: {
      colors: {
        primary: "#ece9e3",
        secondary: "#ece9e3",
        accent: "#8c8a86",
        linkColor: "",
        background: "#0d0d0f",
        surface: "#161618",
        text: "#ece9e3",
        textMuted: "#8c8a86",
        border: "#26262b",
      },
      typography: {
        bodyFont: "Inter",
        headingMode: "split",
        headingFont: "Playfair Display",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 600 },
        headingWeights: { h1: 700, h2: 700, h3: 600 },
      },
      design: {
        density: "spacious",
        contentWidth: "narrow",
        sectionAlign: "center",
        gutter: "airy",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "underline",
        shadowStyle: "none",
        ruleStyle: "hairline",
        imageTreatment: "plain",
        galleryLayout: "masonry",
        headingCase: "none",
        headingTracking: "normal",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#0d0d0f",
        footerStyle: "surface",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-center-nav-below",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: false,
    },
  },
  ember: {
    name: "Ember",
    description: "Warm late-night analog — amber + rust glow on deep espresso.",
    appearance: {
      colors: {
        primary: "#ece2cf",
        secondary: "#d39a44",
        accent: "#c4633a",
        linkColor: "",
        background: "#17120d",
        surface: "#211a12",
        text: "#ece2cf",
        textMuted: "#a08e74",
        border: "#382e22",
      },
      typography: {
        bodyFont: "DM Sans",
        headingMode: "split",
        headingFont: "Bricolage Grotesque",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 600, h2: 600, h3: 600 },
      },
      design: {
        density: "comfortable",
        contentWidth: "medium",
        sectionAlign: "left",
        gutter: "normal",
        radius: "soft",
        buttonShape: "rounded",
        buttonFill: "solid",
        shadowStyle: "glow",
        ruleStyle: "hairline",
        imageTreatment: "framed",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "tight",
        headingScale: "balanced",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#1c130c",
        footerStyle: "surface",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: true,
    },
  },
  redwood: {
    name: "Redwood",
    description: "Misty naturalist — red-bark and sage under a fog-cream sky.",
    appearance: {
      colors: {
        primary: "#7d3a2d",
        secondary: "#7e9376",
        accent: "#7d3a2d",
        linkColor: "",
        background: "#eef0ea",
        surface: "#f7f8f3",
        text: "#33291f",
        textMuted: "#6f6a5e",
        border: "#d8dad0",
      },
      typography: {
        bodyFont: "Libre Franklin",
        headingMode: "split",
        headingFont: "Spectral",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 600 },
        headingWeights: { h1: 500, h2: 500, h3: 500 },
      },
      design: {
        density: "spacious",
        contentWidth: "medium",
        sectionAlign: "left",
        gutter: "normal",
        radius: "soft",
        buttonShape: "rounded",
        buttonFill: "solid",
        shadowStyle: "soft",
        ruleStyle: "hairline",
        imageTreatment: "rounded",
        galleryLayout: "portrait",
        headingCase: "none",
        headingTracking: "normal",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#f7f3ec",
        footerStyle: "inverse",
        grain: false,
      },
    },
    header: {
      headerMode: "transparent-static",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "#ffffff",
      isHeaderTextUppercase: false,
    },
  },
  mahogany: {
    name: "Mahogany",
    description: "Old-world luxe — Bodoni and brass on polished dark wood.",
    appearance: {
      colors: {
        primary: "#f1e7d7",
        secondary: "#c6a45c",
        accent: "#c6a45c",
        linkColor: "",
        background: "#331512",
        surface: "#43201a",
        text: "#f1e7d7",
        textMuted: "#bfa78f",
        border: "#5a2c24",
      },
      typography: {
        bodyFont: "Inter",
        headingMode: "split",
        headingFont: "Bodoni Moda",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 500, h2: 500, h3: 500 },
      },
      design: {
        density: "comfortable",
        contentWidth: "narrow",
        sectionAlign: "center",
        gutter: "normal",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "outline",
        shadowStyle: "none",
        ruleStyle: "accent",
        imageTreatment: "framed",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "normal",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#2a100d",
        footerStyle: "surface",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-static",
      headerLayout: "logo-center-nav-below",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: false,
    },
  },
  oak: {
    name: "Oak",
    description: "Sturdy crafted — golden oak and a slab serif on warm oat.",
    appearance: {
      colors: {
        primary: "#8a5a2b",
        secondary: "#6f6a3c",
        accent: "#8a5a2b",
        linkColor: "",
        background: "#ece1c6",
        surface: "#f6efda",
        text: "#3b3024",
        textMuted: "#877559",
        border: "#d7caa6",
      },
      typography: {
        bodyFont: "DM Sans",
        headingMode: "split",
        headingFont: "Zilla Slab",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 700, h2: 700, h3: 600 },
      },
      design: {
        density: "comfortable",
        contentWidth: "medium",
        sectionAlign: "left",
        gutter: "normal",
        radius: "soft",
        buttonShape: "rounded",
        buttonFill: "solid",
        shadowStyle: "soft",
        ruleStyle: "bold",
        imageTreatment: "framed",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "normal",
        headingScale: "balanced",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#f6efda",
        footerStyle: "inverse",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: true,
    },
  },
  pulse: {
    name: "Pulse",
    description: "Electronic / club — electric blue on a cold technical grid.",
    appearance: {
      colors: {
        primary: "#eef0f2",
        secondary: "#19e2d2",
        accent: "#3358ff",
        linkColor: "",
        background: "#0a0b0d",
        surface: "#14161a",
        text: "#eef0f2",
        textMuted: "#7a808a",
        border: "#23262c",
      },
      typography: {
        bodyFont: "JetBrains Mono",
        headingMode: "split",
        headingFont: "Space Grotesk",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 700, h2: 700, h3: 600 },
      },
      design: {
        density: "compact",
        contentWidth: "wide",
        sectionAlign: "left",
        gutter: "tight",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "solid",
        shadowStyle: "glow",
        ruleStyle: "bold",
        imageTreatment: "plain",
        galleryLayout: "grid",
        headingCase: "upper",
        headingTracking: "wide",
        headingScale: "balanced",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#ffffff",
        footerStyle: "surface",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: true,
    },
  },
  concrete: {
    name: "Concrete",
    description: "Hip-hop / luxe-rap — heavy Archivo and brass on black.",
    appearance: {
      colors: {
        primary: "#f4f4f2",
        secondary: "#e3b341",
        accent: "#e3b341",
        linkColor: "",
        background: "#0c0c0d",
        surface: "#161617",
        text: "#f4f4f2",
        textMuted: "#8a8a86",
        border: "#272727",
      },
      typography: {
        bodyFont: "Archivo",
        headingMode: "single",
        headingFont: "",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 700 },
        headingWeights: { h1: 900, h2: 800, h3: 800 },
      },
      design: {
        density: "comfortable",
        contentWidth: "wide",
        sectionAlign: "left",
        gutter: "normal",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "solid",
        shadowStyle: "hard-offset",
        ruleStyle: "bold",
        imageTreatment: "plain",
        galleryLayout: "grid",
        headingCase: "upper",
        headingTracking: "tight",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#15120a",
        footerStyle: "surface",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: true,
    },
  },
  candy: {
    name: "Candy",
    description: "Bright pop — glossy iridescent gradients and bold Outfit.",
    appearance: {
      colors: {
        primary: "#7b2ff7",
        secondary: "#ff2d7e",
        accent: "#ff2d7e",
        linkColor: "",
        background: "#ffffff",
        surface: "#faf7ff",
        text: "#160a2e",
        textMuted: "#6a6480",
        border: "#ece4ff",
      },
      typography: {
        bodyFont: "Inter",
        headingMode: "split",
        headingFont: "Outfit",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 800, h2: 800, h3: 700 },
      },
      design: {
        density: "comfortable",
        contentWidth: "medium",
        sectionAlign: "center",
        gutter: "normal",
        radius: "round",
        buttonShape: "pill",
        buttonFill: "solid",
        shadowStyle: "glow",
        ruleStyle: "none",
        imageTreatment: "rounded",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "tight",
        headingScale: "balanced",
        accentMode: "gradient",
        accentGradient: { from: "#ff2d7e", via: "#7b2ff7", to: "#3b5bff" },
        onAccent: "#ffffff",
        footerStyle: "inverse",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: false,
    },
  },
  obsidian: {
    name: "Obsidian",
    description: "Metal — blackletter wordmark, crimson, condensed caps, grit.",
    appearance: {
      colors: {
        primary: "#e9e5dd",
        secondary: "#c01530",
        accent: "#c01530",
        linkColor: "",
        background: "#07070a",
        surface: "#121216",
        text: "#c6c9cf",
        textMuted: "#65676d",
        border: "#242428",
      },
      typography: {
        bodyFont: "Inter",
        headingMode: "split",
        headingFont: "Oswald",
        displayFont: "UnifrakturCook",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 700, h2: 700, h3: 600 },
      },
      design: {
        density: "comfortable",
        contentWidth: "medium",
        sectionAlign: "center",
        gutter: "normal",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "solid",
        shadowStyle: "none",
        ruleStyle: "accent",
        imageTreatment: "framed",
        galleryLayout: "grid",
        headingCase: "upper",
        headingTracking: "tight",
        headingScale: "dramatic",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#e9e5dd",
        footerStyle: "surface",
        grain: true,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-center-nav-below",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: true,
    },
  },
  cobalt: {
    name: "Cobalt",
    description: "Modern jazz — Blue Note two-tone, cobalt and ochre on cream.",
    appearance: {
      colors: {
        primary: "#1f3a8a",
        secondary: "#d98a2b",
        accent: "#1f3a8a",
        linkColor: "",
        background: "#f2ede1",
        surface: "#ffffff",
        text: "#1a1c22",
        textMuted: "#6f6a5e",
        border: "#ddd6c6",
      },
      typography: {
        bodyFont: "Inter",
        headingMode: "split",
        headingFont: "Familjen Grotesk",
        displayFont: "",
        bodyWeights: { body: 400, bodyBold: 500 },
        headingWeights: { h1: 700, h2: 700, h3: 600 },
      },
      design: {
        density: "comfortable",
        contentWidth: "medium",
        sectionAlign: "left",
        gutter: "normal",
        radius: "sharp",
        buttonShape: "square",
        buttonFill: "solid",
        shadowStyle: "soft",
        ruleStyle: "bold",
        imageTreatment: "plain",
        galleryLayout: "grid",
        headingCase: "none",
        headingTracking: "tight",
        headingScale: "balanced",
        accentMode: "solid",
        accentGradient: NO_GRADIENT,
        onAccent: "#ffffff",
        footerStyle: "accent",
        grain: false,
      },
    },
    header: {
      headerMode: "solid-sticky",
      headerLayout: "logo-left-nav-right",
      wordmarkSizeAdjust: 0,
      headerForegroundColor: "",
      isHeaderTextUppercase: false,
    },
  },
};

/**
 * Apply a theme onto an existing header config. The palette + typography +
 * design are replaced wholesale by the preset (a fresh copy so the shared
 * constant is never mutated); the header *style* fields are overlaid while the
 * artist-owned `wordmark` and `headerSubtitle` survive untouched.
 */
export function resolveTheme(
  id: ThemeId,
  existingHeader: HeaderConfig,
): { appearance: Appearance; header: HeaderConfig } {
  const preset = THEME_PRESETS[id];
  return {
    appearance: structuredClone(preset.appearance),
    header: { ...existingHeader, ...preset.header },
  };
}
