/**
 * Build-time bundling of the musician-site template.
 *
 * create_site and migrate_site push the template's text files into the
 * artist's new repo. They used to walk `templates/musician-site` on disk
 * at runtime, which needs the template copied into the server bundle and
 * a real filesystem — neither exists on Cloudflare Workers. Instead,
 * `scripts/bundle-template.ts` walks the template once at build time and
 * writes the result as a module the jobs import.
 */

import type { TemplateFile } from "./template-reader";

/** Header that marks the generated module and says how to rebuild it. */
export const GENERATED_HEADER =
  "// GENERATED by apps/web/scripts/bundle-template.ts (npm run generate). Do not edit.";

/**
 * Render the source of the generated module for `files`.
 *
 * The file list is embedded as a JSON string passed to `JSON.parse`: for a
 * multi-megabyte payload that parses faster than an object literal and
 * keeps TypeScript from inferring a type for every entry.
 */
export function renderTemplateModule(files: TemplateFile[]): string {
  const payload = JSON.stringify(JSON.stringify(files));
  return [
    GENERATED_HEADER,
    'import type { TemplateFile } from "@/lib/template-reader";',
    "",
    `export const MUSICIAN_SITE_TEMPLATE_FILES: TemplateFile[] = JSON.parse(${payload});`,
    "",
  ].join("\n");
}
